name: e2e tests
on: [push]
jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          npm ci
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build --prod
          start: npm run ionic-serve
          wait-on: 'http://localhost:8100'
