name: e2e tests
on: [push]
jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          npm ci
      - name: Use coturiv/setup-ionic
        uses: coturiv/setup-ionic@v1
      - name: Run e2e tests
        run: |
          npm run all
