name: e2e tests
on: [push]
jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          npm ci

      - name: Ionic instalation
        uses: coturiv/setup-ionic@v1
      - run: |
         ionic serve
         npx cypress run
  
