name: e2e tests
on: [push]
jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          npm ci
          
      - name: Cypress
        uses: cypress-io/github-action@v2
        with:
          start: ionic serve
          wait-on: http://localhost:8100

      - name: Ionic instalation
        uses: coturiv/setup-ionic@v1
      - run: |
         ionic serve
  
