name: e2e tests
on: [push]
jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          npm ci
          
      - name: Ionic
        uses: coturiv/setup-ionic@v1
          
      - name: Cypress
        uses: cypress-io/github-action@v2
      - run: |
         ionic serve
