# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: "node.js.yml"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        npm ci
        npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cypress-io/github-action@v2
      with:
        distribution: 'adopt' # See 'Supported distributions' for available options
        java-version: 8
    - name: Use coturiv/setup-ionic
      uses: ./
    - name: Electron
      with:
          working-directory: examples/chrome
          
    - uses: actions/upload-artifact@v2
      with:
          name: screenshots-in-electron
          path: examples/chrome/cypress/screenshots
          
          
    - name: Run Ionic project tests e2e with Cypress
      run: |
        ionic start
    
    - run: npx image-size cypress/screenshots/**/*.png
      working-directory: examples/chrome

    - name: Chrome
      uses: ./
      with:
        working-directory: examples/chrome
        browser: chrome

    - uses: actions/upload-artifact@v2
      with:
        name: screenshots-in-chrome
        path: examples/chrome/cypress/screenshots

    - uses: actions/upload-artifact@v2
      with:
        name: video-in-chrome
        path: examples/chrome/cypress/videos

    - run: npx image-size cypress/screenshots/**/*.png
      working-directory: examples/chrome
